### ISSUE TITLE
Better gatekeeper option

### ISSUE THREAD

**Issue by akranga** [agilestacks/hub#10]
README stays that gatekeeper should be disabled if you want to use `hub` CLI.  Which devaluates the whole purpose of the gatekeeper for mac users. Perhaps more pragmatic would be to enable gatekeeper exception:

```
spctl --add /Path/To/Application.app
```

**Comment by arkadijs** [comment]
I'm not sure where did you get the idea of `spctl --add` doing what you think it is doing, probably on the internet, but it is not doing the thing you're suggesting.
Yet I've added an `xattr` command for the impatient reader who didn't read the linked Terraform issue comment.

**Comment by akranga** [comment]
Seems to be rotten. Closing!
